mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_del  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin-123
    url: jdbc:mysql://114.55.137.105:3306/student?serverTimezone=Asia/Shanghai



